ConfigManageTool/urls.py
from django.urls import path
from ConfigManageTool import settings
from django.conf.urls import url, include
from django.contrib import admin


def add_url_prefix():
    return settings.URL_PRE_PATH + "ConfigManageTool/"


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path(add_url_prefix() + 'accounts/', include('django.contrib.auth.urls')),
    path(add_url_prefix(), include('RulesetComparer.urls')),
    path(add_url_prefix(), include('permission.urls')),
    path(add_url_prefix(), include('shared_storage.urls')),
]

RulesetComparer/urls.py
from django.urls import path

from RulesetComparer import views
from django.conf.urls import url, include

app_name = 'RulesetComparer'

ruleset_b2b_pattern = [
    path('create/', views.create_ruleset, name="b2b-create-ruleset"),
    path('update/', views.update_ruleset, name="b2b-update-ruleset"),
    path('scheduler/sync/all', views.get_rulesets_sync_jobs, name="get-rulesets-sync-job"),
    path('scheduler/sync/run', views.run_rulesets_sync_job, name="run-rulesets-sync-job"),
    path('scheduler/sync/create', views.create_rulesets_sync_job, name="create-rulesets-sync-job"),
    path('scheduler/sync/update', views.update_rulesets_sync_job, name="update-rulesets-sync-job"),
    path('scheduler/sync/update_status', views.update_rulesets_sync_job_status, name="update-rulesets-sync-job-status"),
    path('scheduler/sync/delete', views.delete_rulesets_sync_job, name="delete-rulesets-sync-job")
]

ruleset_pattern = [
    path('detail_download/<str:environment_id>/<str:country_id>/<str:ruleset_name>',
         views.ruleset_detail_page, name="rule-detail-download"),
    path('detail/<str:environment_id>/<str:country_id>/<str:ruleset_name>/<str:compare_key>',
         views.ruleset_detail_page, name="rule-detail"),
    path('detail_backup/<str:backup_key>/<str:backup_folder>/<str:ruleset_name>',
         views.ruleset_detail_backup_page, name="rule-detail-backup"),
    path('diff/<str:compare_key>/<str:ruleset_name>',
         views.ruleset_diff_page, name="ruleset-diff-compare-result"),
    path('diff/backup/<str:backup_key>/<str:ruleset_name>', views.ruleset_diff_backup_page, name="ruleset-diff-backup"),
    path('diff/backup/with/server/<str:backup_key>/<str:backup_folder>/<str:ruleset_name>',
         views.ruleset_diff_backup_with_server_page, name="ruleset-diff-backup-with-server"),
    path('apply/to/server',
         views.apply_ruleset_to_server, name="ruleset-apply-to-server"),
]

ruleset_download_pattern = [
    path('', views.rule_download_page, name="ruleset-download-page"),
    path('filter/', views.rule_download_filter_page, name="ruleset-download-filter-page"),
    path('packed/', views.download_rulesets, name="packed-ruleset-download"),

]
ruleset_comparer_pattern = [
    path('select/', views.environment_select_page, name="environment-select"),
    path('diff/<str:compare_key>/<str:rule_name>',
         views.ruleset_diff_page, name="rule-diff"),
    path('report/mail/<str:compare_key>',
         views.send_mail, name="report-send"),
    path('report/download/<str:compare_key>',
         views.download_compare_report, name="report-download")
]

admin_console_ruleset_pattern = [
    path('', views.admin_console_page, name="ruleset-admin-console-index"),
    path('server_log', views.admin_console_server_log_page, name="server-log"),
    path('server_log/<int:log_type>', views.admin_console_server_log_page, name="server-log-type"),
    path('scheduler/list', views.admin_console_report_scheduler_list_page, name="report-scheduler-list"),
    path('scheduler/create', views.admin_console_report_scheduler_create_page, name="task-create"),
    path('scheduler/update/<int:scheduler_id>', views.admin_console_report_scheduler_update_page, name="task-update"),
    path('scheduler/sync/list', views.admin_console_sync_scheduler_list_page, name="sync-scheduler-list"),
    path('scheduler/sync/create', views.admin_console_sync_scheduler_create_page, name="sync-scheduler-create"),
    path('scheduler/sync/update/<int:scheduler_id>', views.admin_console_sync_scheduler_update_page,
         name="sync-scheduler-update"),
    path('recover/filter', views.admin_console_recover_ruleset_filtered_page, name="recover-filter-page"),
    path('recover/filter/environment', views.admin_console_recover_ruleset_filtered_environment_page,
         name="recover-filter-environment-page"),
    path('recover/filter/backup/list', views.admin_console_recover_ruleset_backup_list_page,
         name="recover-filter-backup-list-page"),
    path('recover/rulesets', views.recover_rulesets,
         name="recover-rulesets"),
    path('ruleset_log/list', views.admin_console_ruleset_log_list_page, name="ruleset-log-list"),
    path('ruleset_log/list/filter', views.admin_console_ruleset_log_list_filter_page, name="ruleset-log-list-filter"),
    path('ruleset_log/list/page', views.admin_console_ruleset_log_list_page_change, name="ruleset-log-list-page"),
    path('ruleset_log/detail/<int:log_id>', views.admin_console_ruleset_log_detail_page, name="ruleset-log-detail"),
    path('ruleset_log/detail/ruleset', views.get_ruleset, name="ruleset-log-detail-ruleset"),

]

admin_console_pattern = [
    path('admin_console/module/list', views.get_module_list),
    path('admin_console/module/create', views.create_module),
]

ruleset_scheduler_pattern = [
    path('<int:scheduler_id>', views.get_rulesets_report_job),
    path('list', views.get_rulesets_report_jobs),
    path('run', views.run_ruleset_report_job, name="run-report-scheduler"),
    path('create', views.create_ruleset_report_job, name="create-scheduler"),
    path('update', views.update_ruleset_report_job, name="update-scheduler"),
    path('delete', views.delete_ruleset_report_job, name="delete-scheduler"),
    path('update_status', views.update_rulesets_report_status, name="update-rulesets-report-job-status"),

]

ruleset_test_pattern = [
    path('compare/local', views.compare_ruleset_test),
]

urlpatterns = [
    path('ruleset/test/', include(ruleset_test_pattern)),
    path('ruleset/', include(ruleset_pattern)),
    path('ruleset/b2b/', include(ruleset_b2b_pattern)),
    path('ruleset/download/', include(ruleset_download_pattern)),
    path('ruleset/compare/', include(ruleset_comparer_pattern)),
    path('ruleset/scheduler/', include(ruleset_scheduler_pattern)),
    path('admin_console/ruleset/', include(admin_console_ruleset_pattern)),
]

permission/urls.py
from django.urls import path

from permission import views
from django.conf.urls import include

app_name = 'permission'

permission_pattern = [
    path('', views.permission_index_page, name="permission-index"),

]

user_role_pattern = [
    path('user_role', views.setting_user_role_list_page, name="user-role-list-page"),
    path('user_role/edit', views.edit_user_role, name="user-role-edit"),
    path('user_role/edit/<str:user_id>', views.setting_user_role_edit_page, name="user-role-edit-page"),
]

role_permission_pattern = [
    path('role', views.setting_role_permission_list_page, name="role-permission-list-page"),
    path('role/edit/<str:environment_id>', views.setting_role_permission_edit_page, name="role-permission-edit-page"),
    path('role/edit', views.edit_role_permission, name="role-permission-edit"),

]

configuration_pattern = [
    path('git/country_path/list', views.admin_console_git_country_path_list_page, name="git-country-path-list"),
    path('git/country_path/edit', views.admin_console_git_country_path_edit, name="git-country-path-edit"),
]

urlpatterns = [
    path('admin_console/permission/', include(permission_pattern)),
    path('admin_console/permission/', include(role_permission_pattern)),
    path('admin_console/permission/', include(user_role_pattern)),
    path('admin_console/configuration/', include(configuration_pattern)),

]

shared_storage/urls.py
from django.urls import path

from shared_storage import views
from django.conf.urls import include

app_name = 'shared_storage'

compare_pattern = [
    path('select', views.select_to_compare_page, name="select-to-compare-page"),
    path('result/<str:root_key>', views.select_to_compare_result_page,
         name="select-to-compare-result-page"),
    path('file/diff/<str:root_key>/<str:node_key>/<str:type>', views.select_to_compare_file_diff_page,
         name="select-to-compare-file-diff-page"),
    path('file/detail/<str:side>/<str:root_key>/<str:node_key>/<str:diff_result>/<str:file_type>',
         views.select_to_compare_file_detail_page, name="select-to-compare-file-detail-page"),
    path('mail', views.send_compare_result_mail),
]

download_pattern = [
    path('', views.select_to_download_page, name="select-to-download-page"),
    path('with/filters', views.select_to_download_filter_result_page, name="select-to-download-filter-result"),
    path('with/file/list', views.select_to_download_file_list_page, name="select-to-download-file-list"),
    path('files', views.download_files, name="select-to-download-files"),
    path('exist/files', views.download_exist_files, name="select-to-download-exist-files"),

]

filter_pattern = [
    path('compare/environment', views.select_to_compare_filter_environment,
         name="compare-filter-region-environments"),
    path('download/environment', views.select_to_download_filter_environment,
         name="download-filter-region-environments"),
    path('compare/folder', views.select_to_compare_filter_folder,
         name="compare-filter-environment-folders"),
    path('download/folder', views.select_to_download_filter_folder,
         name="download-filter-environment-folders"),
    path('download/module/folder', views.select_to_download_filter_module_folder,
         name="download-filter-folder-modules"),
    path('download/latest/version/folder', views.select_to_download_filter_latest_version_folder,
         name="download-filter-latest-version-folder"),
]

admin_console_pattern = [
    path('', views.admin_console_page, name="admin-console-index"),
    path('report/scheduler/list', views.admin_console_report_scheduler_list_page, name="report-scheduler-list-page"),
    path('report/scheduler/create', views.admin_console_report_scheduler_create_page,
         name="report-scheduler-create-page"),
    path('report/scheduler/update/<int:scheduler_id>', views.admin_console_report_scheduler_update_page,
         name="report-scheduler-update-page"),
]

admin_console_report_api_pattern = [
    path('run', views.run_report_scheduler_job, name="run-report-scheduler"),
    path('create', views.create_report_scheduler_job, name="create-report-scheduler"),
    path('update', views.update_report_scheduler_job, name="update-report-scheduler"),
    path('delete', views.delete_report_scheduler_job, name="delete-report-scheduler"),
    path('update_status', views.update_report_scheduler_status, name="update-report-scheduler-status"),
]

urlpatterns = [
    path('shared_storage/compare/', include(compare_pattern)),
    path('shared_storage/download/', include(download_pattern)),
    path('shared_storage/filter/', include(filter_pattern)),
    path('shared_storage/report/scheduler/', include(admin_console_report_api_pattern)),
    path('admin_console/shared_storage/', include(admin_console_pattern)),

]

templates/ruleset/backend/admin_console_base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <link href="{% static '/css/fontawesome/all.css' %}" rel="stylesheet">
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static '/css/flat-ui.css' %}" rel="stylesheet">
    <link href="{% static '/css/bootstrap-clockpicker.min.css' %}" rel="stylesheet">
    <link href="{% static '/css/admin_console.css' %}" rel="stylesheet">
    <link href="{% static '/css/main.css' %}" rel="stylesheet">
    <link href="{% static '/css/sweetalert.css' %}" rel="stylesheet">
    <script src="{% static '/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static '/js/sweetalert.min.js' %}"></script>
    <script src="{% static '/js/popper.js' %}"></script>
    <script src="{% static '/js/flat-ui.js' %}"></script>
    <script src="{% static '/js/bootstrap-clockpicker.min.js' %}"></script>
    <script src="{% static '/js/main.js' %}"></script>
    <script src="{% static '/js/rest-client.js' %}"></script>
    {% block resource %}
    {% endblock %}
</head>
<body>
<div class="base_container row">
    <div id="left_area">
        <div id="CMT_icon">
            <img src="{% static '/icons/CMT_icon2.png' %}">
        </div>
        <div id="info">
            <div id="module_info" class="info_block">
                <div class="info_title">MODULE</div>
                <div class="info_content">{{ navigation_info.module_data.current_module.display_name }}</div>
            </div>
        </div>
        <div id="function_list">
            {% if navigation_info.functions_data.server_log.visible or navigation_info.functions_data.ruleset_log.visible %}
                <div id="log_manager_div" class="function_div">
                    <a data-toggle="collapse" href="#log_manager_list_div" role="button" aria-expanded="false"
                       aria-controls="log_manager_list_div">
                        <div class="row no-row-margin">
                            <div class="function_icon_div">
                                <img class="function_icon" src="{% static '/icons/server_log_white.png' %}">
                            </div>
                            <div class="function_text vertical_align_middle">Log Manager</div>
                        </div>
                    </a>
                </div>
                <div id="log_manager_list_div" class="manager_list_div collapse multi-collapse">
                    {% if navigation_info.functions_data.server_log.visible %}
                        <div id="server_log_div">
                            <a href="{% url 'RulesetComparer:server-log' %}">
                                <div class="sub_function_text vertical_align_middle">Server Log</div>
                            </a>
                        </div>
                    {% endif %}
                    {% if navigation_info.functions_data.ruleset_log.visible %}
                        <div id="ruleset_log_div">
                            <a href="{% url 'RulesetComparer:ruleset-log-list' %}">
                                <div class="sub_function_text vertical_align_middle">Ruleset Log</div>
                            </a>
                        </div>
                    {% endif %}
                </div>
            {% endif %}
            {% if navigation_info.functions_data.report_task.visible or navigation_info.functions_data.auto_sync_task.visible %}
                <div id="task_manager_div" class="function_div">
                    <a data-toggle="collapse" href="#task_manager_list_div" role="button" aria-expanded="false"
                       aria-controls="task_manager_list_div">
                        <div class="row no-row-margin">
                            <div class="function_icon_div">
                                <img class="function_icon" src="{% static '/icons/task_manage_white.png' %}">
                            </div>
                            <div class="function_text vertical_align_middle">Task Manager</div>
                        </div>
                    </a>
                </div>
                <div id="task_manager_list_div" class="manager_list_div collapse multi-collapse">
                    {% if navigation_info.functions_data.report_task.visible %}
                        <div id="report_task_div">
                            <a href="{% url 'RulesetComparer:report-scheduler-list' %}">
                                <div class="sub_function_text vertical_align_middle">ReportTask</div>
                            </a>
                        </div>
                    {% endif %}
                    {% if navigation_info.functions_data.auto_sync_task.visible %}
                        <div id="auto_sync_task_div">
                            <a href="{% url 'RulesetComparer:sync-scheduler-list' %}">
                                <div class="sub_function_text vertical_align_middle">AutoSyncTask</div>
                            </a>
                        </div>
                    {% endif %}
                </div>
            {% endif %}
            {% if navigation_info.functions_data.recovery.visible %}
                <div id="recover_function_div" class="function_div">
                    <a href="{% url 'RulesetComparer:recover-filter-page' %}">
                        <div class="row no-row-margin">
                            <div class="function_icon_div">
                                <img id="recover_icon" class="function_icon"
                                     src="{% static '/icons/recover_icon.png' %}">
                            </div>
                            <div class="function_text vertical_align_middle">Recovery</div>
                        </div>
                    </a>
                </div>
            {% endif %}
        </div>
    </div>
    <div id="right_area">
        <div id="nav_bar_top_div" class="row no-row-margin">
            <div id="login_info_div" class="row no-row-margin" data-toggle="dropdown">

                <div id="login_account_div" class="vertical_align_middle">{{ navigation_info.user_data.name }}</div>
                <div id="dropdown_option_div" class="vertical_align_middle">
                    <span id="dropdown_icon_span" class="fui-triangle-down"></span>
                </div>
                <div id="user_action_dropdown_div" class="dropdown-menu" aria-labelledby="login_info_div">
                    <li>
                        <a href="{% url 'password_change' %}" id="reset_password_link" class="dropdown-item">Reset
                            Password</a>
                    </li>
                    {% if navigation_info.module_data.shared_storage.visible == 1 %}
                        <li>
                            <a href="{% url 'shared_storage:admin-console-index' %}" id="shared_storage_module_link"
                               class="dropdown-item">
                                Shared Storage</a>
                        </li>
                    {% endif %}
                    {% if navigation_info.module_data.setting.visible == 1 %}
                        <li>
                            <a href="{% url 'permission:permission-index' %}" id="setting_module_link"
                               class="dropdown-item">
                                Settings</a>
                        </li>
                    {% endif %}
                    <li>
                        <a href="{% url 'logout' %}" id="logout_link" class="dropdown-item">Log Out</a>
                    </li>
                </div>
            </div>
        </div>
        <div id="content_area">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    {% csrf_token %}
</div>
</body>
<script>
    $('#user_action_dropdown_div a').on('click', function () {
        self.location = $(this).attr('href');
    });

    initLoadingGIF("{% static '/icons/loading.gif' %}");
</script>
</html>

templates/ruleset/backend/ruleset_log_detail.html
{% extends "admin_console_base.html" %}
{% load staticfiles %}

{% block resource %}
    <link href="{% static '/css/ruleset_log_detail.css' %}" rel="stylesheet">
    <script src="{% static '/js/adminConsole/ruleset-log-detail.js' %}"></script>
{% endblock %}
{% block content %}
    <div id="ruleset_log_detail_container" class="row no-row-margin">
        <div id="ruleset_detail_top_div" class="row no-row-margin">
            <div id="log_detail_div" class="admin_console_block_background custom_container">
                <div class="header_div row no-row-margin">
                    {% if action.name == 'create' %}
                        <div id="action_div" class="vertical_align_middle"> {% include 'create_action_tag.html' %}</div>
                    {% elif action.name == 'update' %}
                        <div id="action_div" class="vertical_align_middle"> {% include 'update_action_tag.html' %}</div>
                    {% else %}
                        <div id="action_div" class="vertical_align_middle"> {% include 'delete_action_tag.html' %}</div>
                    {% endif %}
                    <div class="component_title vertical_align_middle">{{ ruleset_name }}</div>
                </div>
                <div id="information_div">
                    <div class="row no-row-margin information_row">
                        <div class="col">
                            <div class="row_title_div vertical_align_middle">Log ID</div>
                            <div class="vertical_align_middle row_content_div">{{ log_id }}</div>
                        </div>
                        <div class="col">
                            <div class="row_title_div vertical_align_middle">Task ID</div>
                            <div class="vertical_align_middle row_content_div">1</div>
                        </div>
                        <div class="col">
                            <div class="row_title_div vertical_align_middle">Update Time</div>
                            <div class="vertical_align_middle row_content_div">{{ update_time }}</div>
                        </div>
                    </div>
                    <div class="row no-row-margin information_row">
                        <div class="col">
                            <div class="row_title_div vertical_align_middle">Author</div>
                            <div class="row_content_div vertical_align_middle">{{ user_name }}</div>
                        </div>
                        <div class="col">
                            <div class="row_title_div vertical_align_middle">Country</div>
                            <div class="row_content_div vertical_align_middle">
                                {{ country.full_name }}
                            </div>
                        </div>
                        <div class="col">
                            <div class="row_title_div vertical_align_middle">Commit SHA</div>
                            <div class="row_content_div vertical_align_middle">
                                {{ commit_sha }}
                            </div>
                        </div>
                    </div>
                    <div class="row no-row-margin information_row">
                        <div class="col ">
                            <div class="row_title_div vertical_align_middle">From</div>
                            <div class="row_content_div vertical_align_middle">{{ source_environment.name }}</div>
                        </div>
                        <div class="col">
                            <div class="row_title_div vertical_align_middle">To</div>
                            <div class="row_content_div vertical_align_middle">{{ target_environment.name }}</div>
                        </div>
                        <div class="col">
                            <div class="row_title_div vertical_align_middle">Result</div>
                            <div class="vertical_align_middle row_content_div">{{ status }}</div>
                        </div>
                    </div>
                    {% if exception %}
                        <div class="row no-row-margin information_row">
                            <div class="col">
                                <div class="row_title_div vertical_align_middle">Exception</div>
                                <div id="exception_content" class="vertical_align_middle">{{ exception }}</div>
                            </div>
                        </div>
                    {% endif %}
                    <div id="show_ruleset_div" class="row no-row-margin information_row">
                        <div class="row_title_div vertical_align_middle show_ruleset_div_width">Show Ruleset</div>
                        <div class="show_ruleset_div_width">
                            {% if action.name == "delete" %}
                                <button type="button"
                                        class="disabled btn custom_button btn-sm show_ruleset_button_width">Backup
                                    Applied Version
                                </button>
                            {% else %}
                                <button type="button"
                                        class="btn custom_button btn-sm show_ruleset_button_width"
                                        onclick="getRuleset('source')">Backup Applied Version
                                </button>
                            {% endif %}
                        </div>
                        <div class="show_ruleset_div_width">
                            {% if action.name == "create" %}
                                <button type="button"
                                        class="disabled btn custom_button btn-sm show_ruleset_button_width"
                                >Backup Server Version
                                </button>
                            {% else %}
                                <button type="button"
                                        class="btn custom_button btn-sm show_ruleset_button_width"
                                        onclick="getRuleset('target')"
                                >Backup Server Version
                                </button>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="ruleset_detail_div_source" class="ruleset_detail_div admin_console_block_background custom_container">
            <div class="header_div row no-row-margin">
                <div class="component_title vertical_align_middle">Ruleset Information</div>
                <div class="button_div">
                    <button type="button" class="btn btn-primary btn-sm"
                            onclick="onClickPrettySourceEnv()">
                        Pretty
                    </button>
                    <button type="button" class="btn btn-primary btn-sm" onclick="downloadRuleset()">Download</button>
                    <button type="button" class="btn btn-primary btn-sm" onclick="onClickDiffServerSourceEnv()">Compare With Server
                    </button>
                    {% if action.name == "update" %}
                        <button type="button" class="btn btn-primary btn-sm" onclick="onClickDiffBackup()">
                            Compare Backup Rulesets
                        </button>
                    {% endif %}
                    <button type="button" class="btn btn-primary btn-sm" onclick="applyToServer()">Apply</button>
                </div>
            </div>
            <div id="ruleset_content_div_source" class="ruleset_content_div"></div>
        </div>
        <div id="ruleset_detail_div_target" class="ruleset_detail_div admin_console_block_background custom_container">
            <div class="header_div row no-row-margin">
                <div class="component_title vertical_align_middle">Ruleset Information</div>
                <div class="button_div">
                    <button type="button" class="btn btn-primary btn-sm"
                            onclick="onClickPrettyTargetEnv()">
                        Pretty
                    </button>
                    <button type="button" class="btn btn-primary btn-sm" onclick="downloadRuleset()">Download</button>
                    <button type="button" class="btn btn-primary btn-sm" onclick="onClickDiffServerTargetEnv()">Compare With Server
                    </button>
                    {% if action.name == "update" %}
                        <button type="button" class="btn btn-primary btn-sm" onclick="onClickDiffBackup()">
                            Compare Backup Rulesets
                        </button>
                    {% endif %}
                    <button type="button" class="btn btn-primary btn-sm" onclick="applyToServer()">Apply</button>
                </div>
            </div>
            <div id="ruleset_content_div_target" class="ruleset_content_div"></div>
        </div>
    </div>
    <script>
        $(function () {
            initData('{{ ruleset_name }}', '{{ backup_key }}', '{{ source_environment.id }}', '{{ target_environment.id }}', '{{ country.id }}');
            initUrl("{% url 'RulesetComparer:ruleset-log-detail-ruleset' %}", "{% url 'RulesetComparer:packed-ruleset-download' %}", "{% url 'RulesetComparer:ruleset-apply-to-server' %}");
        });

        function onClickPrettySourceEnv() {
            openNewPage('{% url 'RulesetComparer:rule-detail-backup' backup_key "source" ruleset_name %}');
        }

        function onClickPrettyTargetEnv() {
            openNewPage('{% url 'RulesetComparer:rule-detail-backup' backup_key "target" ruleset_name %}');
        }


        function onClickDiffBackup() {
            openDiffResultPage('{% url 'RulesetComparer:ruleset-diff-backup' backup_key ruleset_name %}');
        }

        function onClickDiffServerSourceEnv() {
            openDiffResultPage('{% url 'RulesetComparer:ruleset-diff-backup-with-server' backup_key "source" ruleset_name %}');
        }

        function onClickDiffServerTargetEnv() {
            openDiffResultPage('{% url 'RulesetComparer:ruleset-diff-backup-with-server' backup_key "target" ruleset_name %}');
        }
    </script>

{% endblock %}

templates/ruleset/backend/server_log.html
{% extends "admin_console_base.html" %}
{% load staticfiles %}
{% block content %}
<div id="server_log_container" class="admin_console_block_background">
    <div class="component_title">LOG TYPE</div>
    <div id="button_list" class="row">
        <div id="debug_log" class="button_div">
            <a href="{% url 'RulesetComparer:server-log-type' 0 %}">
                {% if log_type_key == 0 %}
                <button id="debug_log_btn_on_select" type="button" class="btn btn-outline-primary">Info Log</button>
                {% else %}
                <button type="button" class="btn btn-outline-primary">Info Log</button>
                {% endif %}
            </a>
        </div>
        <div id="info_log" class="button_div">
            <a href="{% url 'RulesetComparer:server-log-type' 1 %}">
                {% if log_type_key == 1 %}
                <button id="info_log_btn_on_select" type="button" class="btn btn-outline-info">Warning Log</button>
                {% else %}
                <button type="button" class="btn btn-outline-info">Warning Log</button>
                {% endif %}
            </a>
        </div>
        <div id="error_log" class="button_div">
            <a href="{% url 'RulesetComparer:server-log-type' 2 %}">
                {% if log_type_key == 2 %}
                <button id="error_log_btn_on_select" type="button" class="btn btn-outline-danger">Error Log</button>
                {% else %}
                <button type="button" class="btn btn-outline-danger">Error Log</button>
                {% endif %}
            </a>
        </div>
    </div>
    <div class="component_title">LOG CONTENT</div>
    <div id="log_content_area">
        {% for log in log_content %}
        {{ log }}
        {% if not forloop.last %}<br/>
        {% else %}
        <br/><br/>
        {% endif %}
        {% endfor %}
    </div>


</div>


{% endblock %}