ConfigManageTool/urls.py
from django.urls import path
from ConfigManageTool import settings
from django.conf.urls import url, include
from django.contrib import admin


def add_url_prefix():
    return settings.URL_PRE_PATH + "ConfigManageTool/"


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path(add_url_prefix() + 'accounts/', include('django.contrib.auth.urls')),
    path(add_url_prefix(), include('RulesetComparer.urls')),
    path(add_url_prefix(), include('permission.urls')),
    path(add_url_prefix(), include('shared_storage.urls')),
]

RulesetComparer/urls.py
from django.urls import path

from RulesetComparer import views
from django.conf.urls import url, include

app_name = 'RulesetComparer'

ruleset_b2b_pattern = [
    path('create/', views.create_ruleset, name="b2b-create-ruleset"),
    path('update/', views.update_ruleset, name="b2b-update-ruleset"),
    path('scheduler/sync/all', views.get_rulesets_sync_jobs, name="get-rulesets-sync-job"),
    path('scheduler/sync/run', views.run_rulesets_sync_job, name="run-rulesets-sync-job"),
    path('scheduler/sync/create', views.create_rulesets_sync_job, name="create-rulesets-sync-job"),
    path('scheduler/sync/update', views.update_rulesets_sync_job, name="update-rulesets-sync-job"),
    path('scheduler/sync/update_status', views.update_rulesets_sync_job_status, name="update-rulesets-sync-job-status"),
    path('scheduler/sync/delete', views.delete_rulesets_sync_job, name="delete-rulesets-sync-job")
]

ruleset_pattern = [
    path('detail_download/<str:environment_id>/<str:country_id>/<str:ruleset_name>',
         views.ruleset_detail_page, name="rule-detail-download"),
    path('detail/<str:environment_id>/<str:country_id>/<str:ruleset_name>/<str:compare_key>',
         views.ruleset_detail_page, name="rule-detail"),
    path('detail_backup/<str:backup_key>/<str:backup_folder>/<str:ruleset_name>',
         views.ruleset_detail_backup_page, name="rule-detail-backup"),
    path('diff/<str:compare_key>/<str:ruleset_name>',
         views.ruleset_diff_page, name="ruleset-diff-compare-result"),
    path('diff/backup/<str:backup_key>/<str:ruleset_name>', views.ruleset_diff_backup_page, name="ruleset-diff-backup"),
    path('diff/backup/with/server/<str:backup_key>/<str:backup_folder>/<str:ruleset_name>',
         views.ruleset_diff_backup_with_server_page, name="ruleset-diff-backup-with-server"),
    path('apply/to/server',
         views.apply_ruleset_to_server, name="ruleset-apply-to-server"),
]

ruleset_download_pattern = [
    path('', views.rule_download_page, name="ruleset-download-page"),
    path('filter/', views.rule_download_filter_page, name="ruleset-download-filter-page"),
    path('packed/', views.download_rulesets, name="packed-ruleset-download"),

]
ruleset_comparer_pattern = [
    path('select/', views.environment_select_page, name="environment-select"),
    path('diff/<str:compare_key>/<str:rule_name>',
         views.ruleset_diff_page, name="rule-diff"),
    path('report/mail/<str:compare_key>',
         views.send_mail, name="report-send"),
    path('report/download/<str:compare_key>',
         views.download_compare_report, name="report-download")
]

admin_console_ruleset_pattern = [
    path('', views.admin_console_page, name="ruleset-admin-console-index"),
    path('server_log', views.admin_console_server_log_page, name="server-log"),
    path('server_log/<int:log_type>', views.admin_console_server_log_page, name="server-log-type"),
    path('scheduler/list', views.admin_console_report_scheduler_list_page, name="report-scheduler-list"),
    path('scheduler/create', views.admin_console_report_scheduler_create_page, name="task-create"),
    path('scheduler/update/<int:scheduler_id>', views.admin_console_report_scheduler_update_page, name="task-update"),
    path('scheduler/sync/list', views.admin_console_sync_scheduler_list_page, name="sync-scheduler-list"),
    path('scheduler/sync/create', views.admin_console_sync_scheduler_create_page, name="sync-scheduler-create"),
    path('scheduler/sync/update/<int:scheduler_id>', views.admin_console_sync_scheduler_update_page,
         name="sync-scheduler-update"),
    path('recover/filter', views.admin_console_recover_ruleset_filtered_page, name="recover-filter-page"),
    path('recover/filter/environment', views.admin_console_recover_ruleset_filtered_environment_page,
         name="recover-filter-environment-page"),
    path('recover/filter/backup/list', views.admin_console_recover_ruleset_backup_list_page,
         name="recover-filter-backup-list-page"),
    path('recover/rulesets', views.recover_rulesets,
         name="recover-rulesets"),
    path('ruleset_log/list', views.admin_console_ruleset_log_list_page, name="ruleset-log-list"),
    path('ruleset_log/list/filter', views.admin_console_ruleset_log_list_filter_page, name="ruleset-log-list-filter"),
    path('ruleset_log/list/page', views.admin_console_ruleset_log_list_page_change, name="ruleset-log-list-page"),
    path('ruleset_log/detail/<int:log_id>', views.admin_console_ruleset_log_detail_page, name="ruleset-log-detail"),
    path('ruleset_log/detail/ruleset', views.get_ruleset, name="ruleset-log-detail-ruleset"),

]

admin_console_pattern = [
    path('admin_console/module/list', views.get_module_list),
    path('admin_console/module/create', views.create_module),
]

ruleset_scheduler_pattern = [
    path('<int:scheduler_id>', views.get_rulesets_report_job),
    path('list', views.get_rulesets_report_jobs),
    path('run', views.run_ruleset_report_job, name="run-report-scheduler"),
    path('create', views.create_ruleset_report_job, name="create-scheduler"),
    path('update', views.update_ruleset_report_job, name="update-scheduler"),
    path('delete', views.delete_ruleset_report_job, name="delete-scheduler"),
    path('update_status', views.update_rulesets_report_status, name="update-rulesets-report-job-status"),

]

ruleset_test_pattern = [
    path('compare/local', views.compare_ruleset_test),
]

urlpatterns = [
    path('ruleset/test/', include(ruleset_test_pattern)),
    path('ruleset/', include(ruleset_pattern)),
    path('ruleset/b2b/', include(ruleset_b2b_pattern)),
    path('ruleset/download/', include(ruleset_download_pattern)),
    path('ruleset/compare/', include(ruleset_comparer_pattern)),
    path('ruleset/scheduler/', include(ruleset_scheduler_pattern)),
    path('admin_console/ruleset/', include(admin_console_ruleset_pattern)),
]

permission/urls.py
from django.urls import path

from permission import views
from django.conf.urls import include

app_name = 'permission'

permission_pattern = [
    path('', views.permission_index_page, name="permission-index"),

]

user_role_pattern = [
    path('user_role', views.setting_user_role_list_page, name="user-role-list-page"),
    path('user_role/edit', views.edit_user_role, name="user-role-edit"),
    path('user_role/edit/<str:user_id>', views.setting_user_role_edit_page, name="user-role-edit-page"),
]

role_permission_pattern = [
    path('role', views.setting_role_permission_list_page, name="role-permission-list-page"),
    path('role/edit/<str:environment_id>', views.setting_role_permission_edit_page, name="role-permission-edit-page"),
    path('role/edit', views.edit_role_permission, name="role-permission-edit"),

]

configuration_pattern = [
    path('git/country_path/list', views.admin_console_git_country_path_list_page, name="git-country-path-list"),
    path('git/country_path/edit', views.admin_console_git_country_path_edit, name="git-country-path-edit"),
]

urlpatterns = [
    path('admin_console/permission/', include(permission_pattern)),
    path('admin_console/permission/', include(role_permission_pattern)),
    path('admin_console/permission/', include(user_role_pattern)),
    path('admin_console/configuration/', include(configuration_pattern)),

]

templates/setting/git_country_path_list.html
{% extends "setting_base.html" %}
{% load staticfiles %}

{% block resource %}
    <link href="{% static '/css/git_country_path_list.css' %}" rel="stylesheet">
    <script src="{% static '/js/adminConsole/git-country-path-list.js' %}"></script>

{% endblock %}
{% block content %}
    <div id="git_path_list_container" class="custom_container admin_console_block_background">
        <div id="header_div" class="row no-row-margin">
            <div class="component_title">Git Path List</div>
            <div id="edit_button_div">
                <a id="edit_button" onclick="onClickButton(this)"
                   class="link-btn btn btn-block btn-lg btn-primary">Edit</a>
            </div>
        </div>
        <div id="list_title_div" class="row no-row-margin">
            <div id="id_title_div" class="id_width title_text vertical_align_middle">
                ID
            </div>
            <div id="module_title_div" class="module_width title_text vertical_align_middle">
                Module
            </div>
            <div id="country_title_div" class="country_width title_text vertical_align_middle">
                Country
            </div>
            <div id="repo_path_title_div" class="repo_width title_text vertical_align_middle">
                Git Repo
            </div>
            <div id="folder_title_div" class="folder_width title_text vertical_align_middle">
                Folder
            </div>
        </div>
        <div id="list_content_div">
            {% for git_country_path in git_country_path_list %}
                <div class="country_row_div row no-row-margin">
                    <div class="id_content_div id_width content_text vertical_align_middle">{{ git_country_path.id }}</div>
                    <div class="module_content_div module_width content_text vertical_align_middle">{{ git_country_path.module_data.display_name }}</div>
                    <div class="country_content_div vertical_align_middle country_width">
                        <div class="row no_row_margin">
                            <img class="task_nation_flag"
                                 src="{% static '/icons/national_flag/'|add:git_country_path.country.icon_file_name %}">
                            <div class="content_text country_name_tips">{{ git_country_path.country.full_name }}
                            </div>
                        </div>
                    </div>
                    <div id="{{ git_country_path.id }}_repo_path_content_div"
                         class="path_content_div repo_width content_text vertical_align_middle">
                        {{ git_country_path.repo_path }}
                    </div>
                    <div id="{{ git_country_path.id }}_repo_path_input_div"
                         class="path_input_div repo_width content_text vertical_align_middle">
                        <input id="{{ git_country_path.id }}_repo_path_input" type="text"
                               value="{{ git_country_path.repo_path }}"
                               placeholder="{{ git_country_path.repo_path }}"
                               class="path_input form-control"/>
                    </div>
                    <div id="{{ git_country_path.id }}_folder_content_div"
                         class="path_content_div folder_width content_text vertical_align_middle">
                        {{ git_country_path.folder }}
                    </div>
                    <div id="{{ git_country_path.id }}_folder_input_div"
                         class="path_input_div folder_width content_text vertical_align_middle">
                        <input id="{{ git_country_path.id }}_folder_input" type="text"
                               value="{{ git_country_path.folder }}"
                               placeholder="{{ git_country_path.folder }}"
                               class="path_input form-control"/>
                    </div>
                </div>
                {% if not forloop.last %}
                    <div class="custom_divider"></div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
    <script>
        $(function () {
            editPathUrl = "{% url 'permission:git-country-path-edit' %}";
            '{% for git_country_path in git_country_path_list %}'
                gitPathIds.push('{{ git_country_path.id }}');
                '{% endfor %}'
        });
    </script>

{% endblock %}

templates/setting/role_permission_edit.html
{% extends "setting_base.html" %}
{% load staticfiles %}

{% block resource %}
    <link href="{% static '/css/role_permission_edit.css' %}" rel="stylesheet">
    <script src="{% static '/js/setting/role-permission-edit.js' %}"></script>
{% endblock %}
{% block content %}
    <div id="role_permission_container" class="custom_container row no-row-margin">
        <div class="environment_role_permission_div white_block_div">
            <div class="title_div row no-row-margin">
                <div class="environment_name_div vertical_align_middle">{{ data.environment.name }}</div>
                <div class="edit_icon_div">
                    <button class="btn btn-info btn-wide" onclick="updateRolePermission({{ data.environment.id }})">
                        Save
                    </button>
                </div>
            </div>
            <div class="function_role_permission_div">
                {% for function_role_permission in data.function_role_permission %}
                    <div class="divider vertical_align_middle"></div>
                    <div class="role_permission_div row no-row-margin">
                        <div class="role_permission_title_div">
                            <div class="function_name_div">{{ function_role_permission.function.name }}</div>
                            <div class="visible_text role_type_enable_text_div vertical_align_middle">Visible</div>
                            <div class="role_type_enable_text_div vertical_align_middle">Editable</div>
                        </div>
                        {% for role_permission in function_role_permission.role_permission %}
                            <div class="role_type_div">
                                <div class="role_type_title">{{ role_permission.role_type.display_name }}</div>
                                {% if  role_permission.visible == 0 %}
                                    <div class="check_box_div">
                                        <label class="checkbox"
                                               for="visible_checkbox_{{ function_role_permission.function.id }}_{{ role_permission.role_type.id }}">
                                            <input type="checkbox" value=""
                                                   id="visible_checkbox_{{ function_role_permission.function.id }}_{{ role_permission.role_type.id }}"
                                                   data-toggle="checkbox" class="visible_checkbox custom-checkbox"><span
                                                class="icons"><span
                                                class="icon-unchecked"></span><span class="icon-checked"></span></span>
                                        </label>
                                    </div>
                                {% else %}
                                    <div class="check_box_div">
                                        <label class="checkbox"
                                               for="visible_checkbox_{{ function_role_permission.function.id }}_{{ role_permission.role_type.id }}">
                                            <input type="checkbox" checked="checked" value=""
                                                   id="visible_checkbox_{{ function_role_permission.function.id }}_{{ role_permission.role_type.id }}"
                                                   data-toggle="checkbox" class="visible_checkbox custom-checkbox"><span
                                                class="icons"><span
                                                class="icon-unchecked"></span><span class="icon-checked"></span></span>
                                        </label>
                                    </div>
                                {% endif %}
                                {% if  role_permission.editable == 0 %}
                                    <div class="check_box_div">
                                        <label class="checkbox"
                                               for="editable_checkbox_{{ function_role_permission.function.id }}_{{ role_permission.role_type.id }}">
                                            <input type="checkbox" value=""
                                                   id="editable_checkbox_{{ function_role_permission.function.id }}_{{ role_permission.role_type.id }}"
                                                   data-toggle="checkbox"
                                                   class="editable_checkbox custom-checkbox"><span
                                                class="icons"><span
                                                class="icon-unchecked"></span><span class="icon-checked"></span></span>
                                        </label>
                                    </div>
                                {% else %}
                                    <div class="check_box_div">
                                        <label class="checkbox"
                                               for="editable_checkbox_{{ function_role_permission.function.id }}_{{ role_permission.role_type.id }}">
                                            <input type="checkbox" checked="checked" value=""
                                                   id="editable_checkbox_{{ function_role_permission.function.id }}_{{ role_permission.role_type.id }}"
                                                   data-toggle="checkbox"
                                                   class="editable_checkbox custom-checkbox"><span
                                                class="icons"><span
                                                class="icon-unchecked"></span><span class="icon-checked"></span></span>
                                        </label>
                                    </div>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <script>
        $(function () {
            init("{% url 'permission:role-permission-edit'%}", "{% url 'permission:role-permission-list-page'%}");
        });
    </script>

{% endblock %}

templates/setting/setting_base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <link href="{% static '/css/fontawesome/all.css' %}" rel="stylesheet">
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static '/css/flat-ui.css' %}" rel="stylesheet">
    <link href="{% static '/css/bootstrap-clockpicker.min.css' %}" rel="stylesheet">
    <link href="{% static '/css/admin_console.css' %}" rel="stylesheet">
    <link href="{% static '/css/main.css' %}" rel="stylesheet">
    <link href="{% static '/css/setting_base.css' %}" rel="stylesheet">
    <link href="{% static '/css/sweetalert.css' %}" rel="stylesheet">
    <script src="{% static '/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static '/js/sweetalert.min.js' %}"></script>
    <script src="{% static '/js/popper.js' %}"></script>
    <script src="{% static '/js/flat-ui.js' %}"></script>
    <script src="{% static '/js/bootstrap-clockpicker.min.js' %}"></script>
    <script src="{% static '/js/main.js' %}"></script>
    <script src="{% static '/js/rest-client.js' %}"></script>
    {% block resource %}
    {% endblock %}
</head>
<body>
<div class="base_container row">
    <div id="left_area">
        <div id="CMT_icon">
            <img src="{% static '/icons/CMT_icon2.png' %}">
        </div>
        <div id="info">
            <div id="module_info" class="info_block">
                <div class="info_title">MODULE</div>
                <div class="info_content">{{ navigation_info.module_data.current_module.display_name }}</div>
            </div>
        </div>
        <div id="function_list">
            {% if navigation_info.functions_data.user_role.visible or navigation_info.functions_data.role_permission.visible %}
                <div id="log_manager_div" class="function_div">
                    <a data-toggle="collapse" href="#log_manager_list_div" role="button" aria-expanded="false"
                       aria-controls="log_manager_list_div">
                        <div class="row no-row-margin">
                            <div class="function_icon_div">
                                <img class="function_icon" src="{% static '/icons/server_log_white.png' %}">
                            </div>
                            <div class="function_text vertical_align_middle">Permission</div>
                        </div>
                    </a>
                </div>
                <div id="log_manager_list_div" class="manager_list_div collapse multi-collapse">
                    {% if navigation_info.functions_data.user_role.visible %}
                        <div id="server_log_div">
                            <a href="{% url 'permission:user-role-list-page' %}">
                                <div class="sub_function_text vertical_align_middle">User Role</div>
                            </a>
                        </div>
                    {% endif %}
                    {% if navigation_info.functions_data.role_permission.visible %}
                        <div id="ruleset_log_div">
                            <a href="{% url 'permission:role-permission-list-page' %}">
                                <div class="sub_function_text vertical_align_middle">Role Permission</div>
                            </a>
                        </div>
                    {% endif %}
                </div>
            {% endif %}
            {% if navigation_info.functions_data.git_path_manager.visible %}
                <div id="configuration_div" class="function_div">
                    <a data-toggle="collapse" href="#configuration_list_div" role="button" aria-expanded="false"
                       aria-controls="configuration_list_div">
                        <div class="row no-row-margin">
                            <div class="function_icon_div">
                                <img class="function_icon" src="{% static '/icons/server_log_white.png' %}">
                            </div>
                            <div class="function_text vertical_align_middle">Configuration</div>
                        </div>
                    </a>
                </div>
                <div id="configuration_list_div" class="manager_list_div collapse multi-collapse">
                    {% if navigation_info.functions_data.git_path_manager.visible %}
                        <div id="server_log_div">
                            <a href="{% url 'permission:git-country-path-list' %}">
                                <div class="sub_function_text vertical_align_middle">Git Path Manager</div>
                            </a>
                        </div>
                    {% endif %}
                </div>
            {% endif %}
        </div>
    </div>
    <div id="right_area">
        <div id="nav_bar_top_div" class="row no-row-margin">
            <div id="login_info_div" class="row no-row-margin" data-toggle="dropdown">

                <div id="login_account_div" class="vertical_align_middle">{{ navigation_info.user_data.name }}</div>
                <div id="dropdown_option_div" class="vertical_align_middle">
                    <span id="dropdown_icon_span" class="fui-triangle-down"></span>
                </div>
                <div id="user_action_dropdown_div" class="dropdown-menu" aria-labelledby="login_info_div">
                    <li>
                        <a href="{% url 'password_change' %}" id="reset_password_link" class="dropdown-item">Reset
                            Password</a>
                    </li>
                    {% if navigation_info.module_data.ruleset.visible == 1 %}
                        <li>
                            <a href="{% url 'RulesetComparer:ruleset-admin-console-index' %}" id="reset_password_link"
                               class="dropdown-item">{{ navigation_info.module_data.ruleset.display_name }}</a>
                        </li>
                    {% endif %}

                    <li>
                        <a href="{% url 'logout' %}" id="logout_link" class="dropdown-item">Log Out</a>
                    </li>
                </div>
            </div>
        </div>
        <div id="content_area">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    {% csrf_token %}
</div>
</body>
<script>
    $('#user_action_dropdown_div a').on('click', function () {
        self.location = $(this).attr('href');
    });

    initLoadingGIF("{% static '/icons/loading.gif' %}");
</script>
</html>

templates/setting/user_role_edit.html
{% extends "setting_base.html" %}
{% load staticfiles %}

{% block resource %}
    <link href="{% static '/css/user_role_edit.css' %}" rel="stylesheet">
    <script src="{% static '/js/setting/user-role-edit.js' %}"></script>

{% endblock %}
{% block content %}
    <div id="user_role_edit_container" class="white_block_div custom_container row no-row-margin">
        <div id="title_row_div" class="row no-row-margin">
            <div id="user_name_div" class="vertical_align_middle">{{ data.user_data.name }}</div>
            <div id="save_button_div">
                <button id="update_user_role_button" class="btn btn-default btn-primary btn-wide" onclick="updateUserRole({{ data.user_data.id }})">
                    Save
                </button>
            </div>
        </div>
        <div class="divider"></div>
        {% for role_data in data.environment_role %}
            <div class="environment_roles_div">
            <div class="environment_title_div">{{ role_data.environment.name }}</div>
            <div class="checkbox_group_div row no-row-margin">
                {% for checkbox_data in role_data.role_type %}
                    <div class="user_role_option checkbox_outer_div">
                    {% if checkbox_data.checked %}
                        <div id="checkbox_div_{{ role_data.environment.id }}_{{ checkbox_data.id }}"
                             class="checkbox_div_checked">
                        <label class="radio" for="radio_{{ role_data.environment.id }}_{{ checkbox_data.id }}">
                            <input type="radio" name="radio_group_{{ role_data.environment.name }}" value=""
                                   id="radio_{{ role_data.environment.id }}_{{ checkbox_data.id }}" data-toggle="radio"
                                   class="custom-radio" checked="checked"><span
                                class="icons"><span
                                class="icon-unchecked"></span><span
                                class="icon-checked"></span></span>
                            {{ checkbox_data.display_name }}
                        </label>
                    {% else %}
                        <div id="checkbox_div_{{ role_data.environment.id }}_{{ checkbox_data.id }}"
                             class="user_role_option checkbox_div">
                        <label class="radio" for="radio_{{ role_data.environment.id }}_{{ checkbox_data.id }}">
                            <input type="radio" name="radio_group_{{ role_data.environment.name }}" value=""
                                   id="radio_{{ role_data.environment.id }}_{{ checkbox_data.id }}" data-toggle="radio"
                                   class="custom-radio"><span class="icons"><span
                                class="icon-unchecked"></span><span
                                class="icon-checked"></span></span>
                            {{ checkbox_data.display_name }}
                        </label>
                    {% endif %}
                </label>
                </div>
                </div>
                {% endfor %}
                </div>
            </div>
            {% if not forloop.last %}
                <div class="environment_divider"></div>
            {% endif %}
        {% endfor %}
        </div>

        <script>
            $(function () {
                init("{% url 'permission:user-role-edit'%}", "{% url 'permission:user-role-list-page'%}");

                $('input[type="radio"]').on('change', function () {
                    let name = this.name;
                    let elements = document.getElementsByName(name);
                    let i;
                    for (i = 0; i < elements.length; i++) {
                        console.log("remove checkbox_div_checked");
                        let element = elements[i];
                        let id = element.id;
                        let environmentId = split_str(id, 1);
                        let roleTypeId = split_str(id, 2);
                        let removed_div = document.getElementById("checkbox_div_" + environmentId + "_" + roleTypeId);

                        if (element.checked) {
                            removed_div.classList.remove("checkbox_div");
                            removed_div.classList.add("checkbox_div_checked");
                        } else {
                            removed_div.classList.remove("checkbox_div_checked");
                            removed_div.classList.add("checkbox_div");
                        }
                    }
                });
            });

        </script>

{% endblock %}