ConfigManageTool/urls.py
from django.urls import path
from ConfigManageTool import settings
from django.conf.urls import url, include
from django.contrib import admin


def add_url_prefix():
    return settings.URL_PRE_PATH + "ConfigManageTool/"


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path(add_url_prefix() + 'accounts/', include('django.contrib.auth.urls')),
    path(add_url_prefix(), include('RulesetComparer.urls')),
    path(add_url_prefix(), include('permission.urls')),
    path(add_url_prefix(), include('shared_storage.urls')),
]

RulesetComparer/urls.py
from django.urls import path

from RulesetComparer import views
from django.conf.urls import url, include

app_name = 'RulesetComparer'

ruleset_b2b_pattern = [
    path('create/', views.create_ruleset, name="b2b-create-ruleset"),
    path('update/', views.update_ruleset, name="b2b-update-ruleset"),
    path('scheduler/sync/all', views.get_rulesets_sync_jobs, name="get-rulesets-sync-job"),
    path('scheduler/sync/run', views.run_rulesets_sync_job, name="run-rulesets-sync-job"),
    path('scheduler/sync/create', views.create_rulesets_sync_job, name="create-rulesets-sync-job"),
    path('scheduler/sync/update', views.update_rulesets_sync_job, name="update-rulesets-sync-job"),
    path('scheduler/sync/update_status', views.update_rulesets_sync_job_status, name="update-rulesets-sync-job-status"),
    path('scheduler/sync/delete', views.delete_rulesets_sync_job, name="delete-rulesets-sync-job")
]

ruleset_pattern = [
    path('detail_download/<str:environment_id>/<str:country_id>/<str:ruleset_name>',
         views.ruleset_detail_page, name="rule-detail-download"),
    path('detail/<str:environment_id>/<str:country_id>/<str:ruleset_name>/<str:compare_key>',
         views.ruleset_detail_page, name="rule-detail"),
    path('detail_backup/<str:backup_key>/<str:backup_folder>/<str:ruleset_name>',
         views.ruleset_detail_backup_page, name="rule-detail-backup"),
    path('diff/<str:compare_key>/<str:ruleset_name>',
         views.ruleset_diff_page, name="ruleset-diff-compare-result"),
    path('diff/backup/<str:backup_key>/<str:ruleset_name>', views.ruleset_diff_backup_page, name="ruleset-diff-backup"),
    path('diff/backup/with/server/<str:backup_key>/<str:backup_folder>/<str:ruleset_name>',
         views.ruleset_diff_backup_with_server_page, name="ruleset-diff-backup-with-server"),
    path('apply/to/server',
         views.apply_ruleset_to_server, name="ruleset-apply-to-server"),
]

ruleset_download_pattern = [
    path('', views.rule_download_page, name="ruleset-download-page"),
    path('filter/', views.rule_download_filter_page, name="ruleset-download-filter-page"),
    path('packed/', views.download_rulesets, name="packed-ruleset-download"),

]
ruleset_comparer_pattern = [
    path('select/', views.environment_select_page, name="environment-select"),
    path('diff/<str:compare_key>/<str:rule_name>',
         views.ruleset_diff_page, name="rule-diff"),
    path('report/mail/<str:compare_key>',
         views.send_mail, name="report-send"),
    path('report/download/<str:compare_key>',
         views.download_compare_report, name="report-download")
]

admin_console_ruleset_pattern = [
    path('', views.admin_console_page, name="ruleset-admin-console-index"),
    path('server_log', views.admin_console_server_log_page, name="server-log"),
    path('server_log/<int:log_type>', views.admin_console_server_log_page, name="server-log-type"),
    path('scheduler/list', views.admin_console_report_scheduler_list_page, name="report-scheduler-list"),
    path('scheduler/create', views.admin_console_report_scheduler_create_page, name="task-create"),
    path('scheduler/update/<int:scheduler_id>', views.admin_console_report_scheduler_update_page, name="task-update"),
    path('scheduler/sync/list', views.admin_console_sync_scheduler_list_page, name="sync-scheduler-list"),
    path('scheduler/sync/create', views.admin_console_sync_scheduler_create_page, name="sync-scheduler-create"),
    path('scheduler/sync/update/<int:scheduler_id>', views.admin_console_sync_scheduler_update_page,
         name="sync-scheduler-update"),
    path('recover/filter', views.admin_console_recover_ruleset_filtered_page, name="recover-filter-page"),
    path('recover/filter/environment', views.admin_console_recover_ruleset_filtered_environment_page,
         name="recover-filter-environment-page"),
    path('recover/filter/backup/list', views.admin_console_recover_ruleset_backup_list_page,
         name="recover-filter-backup-list-page"),
    path('recover/rulesets', views.recover_rulesets,
         name="recover-rulesets"),
    path('ruleset_log/list', views.admin_console_ruleset_log_list_page, name="ruleset-log-list"),
    path('ruleset_log/list/filter', views.admin_console_ruleset_log_list_filter_page, name="ruleset-log-list-filter"),
    path('ruleset_log/list/page', views.admin_console_ruleset_log_list_page_change, name="ruleset-log-list-page"),
    path('ruleset_log/detail/<int:log_id>', views.admin_console_ruleset_log_detail_page, name="ruleset-log-detail"),
    path('ruleset_log/detail/ruleset', views.get_ruleset, name="ruleset-log-detail-ruleset"),

]

admin_console_pattern = [
    path('admin_console/module/list', views.get_module_list),
    path('admin_console/module/create', views.create_module),
]

ruleset_scheduler_pattern = [
    path('<int:scheduler_id>', views.get_rulesets_report_job),
    path('list', views.get_rulesets_report_jobs),
    path('run', views.run_ruleset_report_job, name="run-report-scheduler"),
    path('create', views.create_ruleset_report_job, name="create-scheduler"),
    path('update', views.update_ruleset_report_job, name="update-scheduler"),
    path('delete', views.delete_ruleset_report_job, name="delete-scheduler"),
    path('update_status', views.update_rulesets_report_status, name="update-rulesets-report-job-status"),

]

ruleset_test_pattern = [
    path('compare/local', views.compare_ruleset_test),
]

urlpatterns = [
    path('ruleset/test/', include(ruleset_test_pattern)),
    path('ruleset/', include(ruleset_pattern)),
    path('ruleset/b2b/', include(ruleset_b2b_pattern)),
    path('ruleset/download/', include(ruleset_download_pattern)),
    path('ruleset/compare/', include(ruleset_comparer_pattern)),
    path('ruleset/scheduler/', include(ruleset_scheduler_pattern)),
    path('admin_console/ruleset/', include(admin_console_ruleset_pattern)),
]

permission/urls.py
from django.urls import path

from permission import views
from django.conf.urls import include

app_name = 'permission'

permission_pattern = [
    path('', views.permission_index_page, name="permission-index"),

]

user_role_pattern = [
    path('user_role', views.setting_user_role_list_page, name="user-role-list-page"),
    path('user_role/edit', views.edit_user_role, name="user-role-edit"),
    path('user_role/edit/<str:user_id>', views.setting_user_role_edit_page, name="user-role-edit-page"),
]

role_permission_pattern = [
    path('role', views.setting_role_permission_list_page, name="role-permission-list-page"),
    path('role/edit/<str:environment_id>', views.setting_role_permission_edit_page, name="role-permission-edit-page"),
    path('role/edit', views.edit_role_permission, name="role-permission-edit"),

]

configuration_pattern = [
    path('git/country_path/list', views.admin_console_git_country_path_list_page, name="git-country-path-list"),
    path('git/country_path/edit', views.admin_console_git_country_path_edit, name="git-country-path-edit"),
]

urlpatterns = [
    path('admin_console/permission/', include(permission_pattern)),
    path('admin_console/permission/', include(role_permission_pattern)),
    path('admin_console/permission/', include(user_role_pattern)),
    path('admin_console/configuration/', include(configuration_pattern)),

]

templates/ruleset/frontend/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <link href="{% static '/css/fontawesome/all.css' %}" rel="stylesheet">
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static '/css/flat-ui.css' %}" rel="stylesheet">
    <link href="{% static '/css/main.css' %}" rel="stylesheet">
    <link href="{% static '/css/sweetalert.css' %}" rel="stylesheet">
    <script src="{% static '/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static '/js/popper.js' %}"></script>
    <script src="{% static '/js/flat-ui.js' %}"></script>
    <script src="{% static '/js/application.js' %}"></script>
    <script src="{% static '/js/sweetalert.min.js' %}"></script>
    <script src="{% static '/js/main.js' %}"></script>
    <script src="{% static '/js/rest-client.js' %}"></script>
    {% block resource %}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-default navbar-expand-lg" role="navigation">
    <a class="navbar-brand" href="#">Ruleset Manager</a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse-01"></button>
    <div class="collapse navbar-collapse" id="navbar-collapse-01">
        <ul class="nav navbar-nav mr-auto">
            <li class="active"><a href="{% url 'RulesetComparer:environment-select' %}">Compare</a></li>
            <li class="active"><a href="{% url 'RulesetComparer:ruleset-download-page' %}">Download</a></li>
        </ul>
    </div>
</nav>
{% csrf_token %}
{% block content %}
{% endblock %}
</body>
<script>
    initLoadingGIF("{% static '/icons/loading.gif' %}");
</script>
</html>

templates/ruleset/frontend/rule_download.html
{% extends "base.html" %}
{% load staticfiles %}

{% block resource %}
    <link href="{% static '/css/rule_download.css' %}" rel="stylesheet">
    <script src="{% static '/js/rule-download.js' %}"></script>
{% endblock %}
{% block content %}
    <div id="rule_download_container" class="height-full">
        <div id="select_data_div">
            <div class="div_title_text">SELECT
            </div>

            <div id="select_country_and_env_div" class="custom-row">
                <div id="select_country_div" class="col no-col-padding">
                    <label class="drop_down_label_text col no-col-padding" for="select_country">Country</label>
                    <div id="select_country" class="custom-btn-group-1 btn-group">
                        <button id="select-country-btn" class="drop_down_button btn btn-inverse dropdown-toggle"
                                type="button" data-toggle="dropdown">
                            Country
                        </button>
                        <ul id="select-country-list" class="dropdown-limit dropdown-menu dropdown-menu-inverse"
                            role="menu">
                            {% for data in countries %}
                                <li value="{{ data.id }}"><a href="#">{{ data.full_name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div id="select_env_div" class="col no-col-padding">
                    <label class="drop_down_label_text col no-col-padding"
                           for="select_env_drop_down_div">Environment</label>
                    <div id="select_env_drop_down_div" class="custom-btn-group-1 btn-group">
                        <button id="select-env-btn" class="drop_down_button btn btn-inverse dropdown-toggle"
                                type="button"
                                data-toggle="dropdown">
                            Environment
                        </button>
                        <ul id="select-env-list" class="dropdown-limit dropdown-menu dropdown-menu-inverse"
                            role="menu">
                            {% for data in environments %}
                                <li value="{{ data.id }}"><a href="#">{{ data.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div id="filter_div">
                <div id="filter_input_div" class="tagsinput-primary">
                    <label class="drop_down_label_text col no-col-padding"
                           for="filter_tags_input">Filter(Optional)</label>
                    <input id="filter_tags_input" name="tagsinput" class="tagsinput" data-role="tagsinput"
                           placeholder="ex.RS_ROOT"
                           style="display: none;">
                </div>
            </div>
            <div id="filter_btn_div">
                <button id="filter_btn" class="btn btn-default btn-wide" onclick="filterBtnOnClick()">
                    Search
                </button>
            </div>
        </div>
        <div id="download_data_background_div">
            <div id="download_data_div">
                <div id="title_icon_div" class="row no-row-margin">
                    <div class="div_title_text col-4 no-col-padding">DOWNLOAD</div>
                    <div class="row no_row_margin col-8 no-col-padding">
                        <div id="icon_div" class="row no_row_margin">
                            <div id="download_selected_btn_div" class="download-icon col-1 no-col-padding">
                                <button id="download_selected_btn" class="btn btn-info btn-font-13"
                                        onclick="downloadSelectedRulesOnClick()">
                                </button>
                            </div>
                            <div id="download_all_btn_div" class="download-icon col-1 no-col-padding">
                                <button class="btn btn-primary btn-font-13" onclick="downloadAllRulesOnClick()">Download
                                    All
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="rule_name_table_div">
                    <div id="show_rule_name_list_title_div">
                        <div class="title_div row no-row-margin">
                            <div id="table_title_checkbox" class="checkbox_space_set title_text vertical_align_middle">
                                Checked
                            </div>
                            <div id="table_title_ruleset_name"
                                 class="rule_name_space_set title_text vertical_align_middle">
                                RuleSet Name
                            </div>
                            <div id="table_title_action" class="action_space_set title_text vertical_align_middle">
                            </div>
                        </div>
                    </div>
                    <div id="show_rule_name_list_div">
                        {{ rule_name_list }}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        filterBtnOnClick = function () {
            filterRules("{% url 'RulesetComparer:ruleset-download-filter-page' %}");
        };

        downloadAllRulesOnClick = function () {
            downloadAllRules("{% url 'RulesetComparer:packed-ruleset-download' %}");
        };

        downloadSelectedRulesOnClick = function () {
            downloadSelectedRules("{% url 'RulesetComparer:packed-ruleset-download' %}");
        };
    </script>
{% endblock %}

templates/ruleset/frontend/rule_item_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block resource %}
    <link href="{% static '/css/rule_item_list.css' %}" rel="stylesheet">
    <script src="{% static '/js/rule-item-list.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container-rule-list-item container-fluid">
        <div class="row rule_list_item_header">
            <div class="search_bar">
                <div class="input-group">
                    <input type="text" class="search_bar_input form-control" placeholder="Search" id="search-query-3">
                    <span class="input-group-btn">
                    <button type="submit" class="search_bar_button btn"><span class="fui-search"></span></button>
                  </span>
                </div>
            </div>
            <div class="icon_list">
                <div class="row icon_row">
                    <div class="icon_mail_border">
                        <a href="{% url 'RulesetComparer:report-send' compare_hash_key %}">
                            <i class="icon_mail far fa-envelope"></i>
                        </a>
                    </div>
                    <div class="icon_download_border">
                        <a href="{% url 'RulesetComparer:report-download' compare_hash_key %}">
                            <i class="icon_download fas fa-download"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="row rule_list_item_header_information">
            <div class="rule_list_item_info">
                <div class="green_boarder_info_div">
                    <div class="nav green_boarder_nav" data-target=".add_data">
                        <div>
                            <i class="info_nav_icon fas fa-align-justify"></i>
                        </div>
                        <div class="info_nav_title file_title"> Information
                        </div>
                    </div>
                    <div class="content">
                        <div class="custom-row info_row">
                            <div class="info_title">Country</div>
                            <div class="info_content">{{ country.full_name }}</div>
                        </div>
                        <div class="custom-row info_row">
                            <div class="info_title">Environment (1)</div>
                            <div class="info_content">{{ base_env.name }}</div>
                        </div>
                        <div class="custom-row info_row">
                            <div class="info_title">Environment (2)</div>
                            <div class="info_content">{{ compare_env.name }}</div>
                        </div>
                        <div class="custom-row info_row">
                            <div class="info_title">Compared Time</div>
                            <div class="info_content">{{ current_time }}</div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="rule_list_item_summary">
                <div class="green_boarder_info_div">
                    <div class="nav green_boarder_nav" data-target=".add_data">
                        <div>
                            <i class="info_nav_icon fas fa-align-justify"></i>
                        </div>
                        <div class="info_nav_title file_title"> Summary
                        </div>
                    </div>
                    <div class="content">
                        <div class="custom-row info_row_margin_top info_row_bg_blue">
                            <div class="summary_title"></div>
                            <div class="summary_header_content">{{ base_env.name }}</div>
                            <div class="summary_header_content">{{ compare_env.name }}</div>
                        </div>
                        <div class="custom-row info_row_no_margin">
                            <div class="summary_title">Common Rule Set</div>
                            <div class="summary_content_column_two">{{ normal_list|length }}</div>
                        </div>
                        <div class="custom-row info_row_no_margin">
                            <div class="summary_title">Rule Set Only</div>
                            {% if remove_file_count == add_file_count %}
                                <div class="summary_content_column_two">{{ add_file_count }}</div>
                            {% else %}
                                <div class="summary_content summary_content_highlight">{{ remove_file_count }}</div>
                                <div class="summary_content summary_content_highlight">{{ add_file_count }}</div>
                            {% endif %}
                        </div>
                        <div class="custom-row info_row_no_margin">
                            <div class="summary_title">Rule Only</div>
                            {% if remove_rule_count == add_rule_count %}
                                <div class="summary_content_column_two">{{ add_rule_count }}</div>
                            {% else %}
                                <div class="summary_content summary_content_highlight">{{ remove_rule_count }}</div>
                                <div class="summary_content summary_content_highlight">{{ add_rule_count }}</div>
                            {% endif %}
                        </div>
                        <div class="custom-row info_row_no_margin">
                            <div class="summary_title">Different Rule Sets</div>
                            {% if modify_file_count == 0 %}
                                <div class="summary_content_column_two">{{ modify_file_count }}</div>
                            {% else %}
                                <div class="summary_content_column_two summary_content_highlight">{{ modify_file_count }}</div>
                            {% endif %}
                        </div>
                        <div class="custom-row info_row_no_margin">
                            <div class="summary_title summary_title_last">Different Rules</div>
                            {% if modify_rule_count == 0 %}
                                <div class="summary_content_column_two summary_content_last">{{ modify_rule_count }}</div>
                            {% else %}
                                <div class="summary_content_column_two summary_content_last summary_content_highlight">
                                    {{ modify_rule_count }}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="rule_list_item">
            <div class="add_list">
                <div class="nav" data-toggle="collapse" data-target=".add_data">
                    <div class="nav_title"> {{ compare_env.name }} Only
                        <span class="fui-triangle-down"></span>
                    </div>
                </div>
                {% for data in add_list %}
                    <div class="collapse add_data data row">
                        {% include 'rule_item_list_count.html' %}
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="rule_list_item">
            <div class="minus_list">
                <div class="nav" data-toggle="collapse" data-target=".minus_data">
                    <div class="nav_title">  {{ base_env.name }} Only
                        <span class="fui-triangle-down"></span>
                    </div>
                </div>
                {% for data in remove_list %}
                    <div class="collapse minus_data data row">
                        {% include 'rule_item_list_count.html' %}
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="rule_list_item">
            <div class="modify_list">
                <div class="nav" data-toggle="collapse" data-target=".modify_data">
                    <div class="nav_title"> Different Files
                        <span class="fui-triangle-down"></span>
                    </div>
                </div>
                {% for data in modify_list %}
                    <div class="collapse modify_data data row">
                        {% include 'rule_item_list_count.html' %}
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="rule_list_item">
            <div class="normal_list">
                <div class="nav" data-toggle="collapse" data-target=".normal_data">
                    <div class="nav_title"> Common Files
                        <span class="fui-triangle-down"></span>
                    </div>
                </div>
                {% for data in normal_list %}
                    <div class="collapse normal_data data row">
                        {% include 'rule_item_list_count.html' %}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

templates/ruleset/frontend/rule_show_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block resource %}
    <script src="{% static '/js/rule-show-detail.js' %}"></script>
{% endblock %}
{% load filters %}
{% block content %}
    <div class="container-rule-detail container-fluid">
        <div class="row rule_detail_header">
            <div class="search_bar">
                <div class="input-group">
                    <input type="text" class="search_bar_input form-control" placeholder="Search" id="search-query-3">
                    <span class="input-group-btn">
                    <button type="submit" class="search_bar_button btn"><span class="fui-search"></span></button>
                  </span>
                </div>
            </div>
            <div class="icon_list">
                <div class="row icon_row">
                    <div class="icon_download_border" onclick="downloadSelectedRulesOnClick()">
                        <i class="icon_download fas fa-download"></i>
                    </div>
                </div>
            </div>
        </div>
        <div class="rule_detail_info">
            <div class="green_boarder_info_div">
                <div class="nav green_boarder_nav" data-target=".add_data">
                    <div>
                        <i class="info_nav_icon fas fa-align-justify"></i>
                    </div>
                    <div class="info_nav_title file_title"> Information
                    </div>
                </div>
                <div class="content">
                    <div class="custom-row info_row">
                        <div class="info_title">Environment</div>
                        <div class="info_content">{{ environment.name }}</div>
                    </div>
                    <div class="custom-row info_row">
                        <div class="info_title">Country</div>
                        <div class="info_content">{{ country.name }}</div>
                    </div>
                    <div class="custom-row info_row">
                        <div class="info_title">Name</div>
                        <div class="info_content">{{ ruleset_name }}</div>
                    </div>
                    <div class="custom-row info_row">
                        <div class="info_title">Total</div>
                        <div class="info_content">{{ ruleset_data|length }}</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row rule_detail_list">
            <div class="green_boarder_list_div">
                <div class="nav green_boarder_nav" data-target=".add_data">
                    <div>
                        <i class="info_nav_icon fas fa-align-justify"></i>
                    </div>
                    <div class="info_nav_title file_title"> Rules
                    </div>
                </div>
                <div class="add_rules">
                    {% for data in ruleset_data %}
                        <div id="process_line" class="row rule_data_line">
                            <div class="rule_data_title">Process</div>
                            <div class="col-9 rule_data_value">{{ data.process }}</div>
                        </div>
                        <div class="line_divider"></div>
                        <div id="process_step_line" class="row rule_data_line">
                            <div class="rule_data_title">Process Step</div>
                            <div class="col-9 rule_data_value">{{ data.process_step }}</div>
                        </div>
                        <div class="line_divider"></div>
                        <div id="org_id_line" class="row rule_data_line">
                            <div class="rule_data_title">Organization ID</div>
                            <div class="col-9 rule_data_value">{{ data.organization_id }}</div>
                        </div>
                        <div class="line_divider"></div>
                        <div id="owner_role_line" class="row rule_data_line">
                            <div class="rule_data_title">Owner Role</div>
                            <div class="col-9 rule_data_value">{{ data.owner_role }}</div>
                        </div>
                        <div class="line_divider"></div>
                        <div id="rule_type_line" class="row rule_data_line">
                            <div class="rule_data_title">Rule Type</div>
                            <div class="col-9 rule_data_value">{{ data.rule_type }}</div>
                        </div>
                        <div class="line_divider"></div>
                        <div id="rule_key_line" class="row rule_data_line">
                            <div class="rule_data_title">Rule Key</div>
                            <div class="col-9 rule_data_value">{{ data.key }}</div>
                        </div>
                        <div class="line_divider"></div>
                        <div id="rule_value_line" class="row rule_data_line">
                            <div class="rule_data_title">Rule Value</div>
                            <div class="col-9 rule_data_value">
                                {% for value in data.value %}
                                    {{ value }}{% if not forloop.last %},<br/>{% endif %}
                                {% endfor %}
                            </div>
                        </div>
                        <div class="line_divider"></div>
                        <div id="rule_expression_line" class="row rule_data_line">
                            <div class="rule_data_title">Rule Expression</div>
                            <div class="col-9 rule_data_value">
                                {% for expression in data.expression %}
                                    {{ expression }}{% if not forloop.last %},<br/>{% endif %}
                                {% endfor %}
                            </div>
                        </div>
                        {% if not forloop.last %}
                            <div class="end_divider"></div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <script>
    $(function () {
        initData(
            "{{ ruleset_path_info.compare_hash_key }}",
            "{{ ruleset_path_info.backup_key }}",
            "{{ ruleset_path_info.backup_folder }}",
            "{{ country.id }}", "{{ environment.id }}", "{{ ruleset_name }}"
        );
    });

        downloadSelectedRulesOnClick = function () {
            downloadRulesFromServer("{% url 'RulesetComparer:packed-ruleset-download' %}");
        }
    </script>
{% endblock %}

templates/ruleset/frontend/ruleset_sync_result_table.html
<tr>
    <td class="td_title">{{ data.ruleset_name }}</td>
    <td class="td_content">{{ data.action }}</td>
</tr>