ConfigManageTool/urls.py
from django.urls import path
from ConfigManageTool import settings
from django.conf.urls import url, include
from django.contrib import admin


def add_url_prefix():
    return settings.URL_PRE_PATH + "ConfigManageTool/"


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path(add_url_prefix() + 'accounts/', include('django.contrib.auth.urls')),
    path(add_url_prefix(), include('RulesetComparer.urls')),
    path(add_url_prefix(), include('permission.urls')),
    path(add_url_prefix(), include('shared_storage.urls')),
]

permission/urls.py
from django.urls import path

from permission import views
from django.conf.urls import include

app_name = 'permission'

permission_pattern = [
    path('', views.permission_index_page, name="permission-index"),

]

user_role_pattern = [
    path('user_role', views.setting_user_role_list_page, name="user-role-list-page"),
    path('user_role/edit', views.edit_user_role, name="user-role-edit"),
    path('user_role/edit/<str:user_id>', views.setting_user_role_edit_page, name="user-role-edit-page"),
]

role_permission_pattern = [
    path('role', views.setting_role_permission_list_page, name="role-permission-list-page"),
    path('role/edit/<str:environment_id>', views.setting_role_permission_edit_page, name="role-permission-edit-page"),
    path('role/edit', views.edit_role_permission, name="role-permission-edit"),

]

configuration_pattern = [
    path('git/country_path/list', views.admin_console_git_country_path_list_page, name="git-country-path-list"),
    path('git/country_path/edit', views.admin_console_git_country_path_edit, name="git-country-path-edit"),
]

urlpatterns = [
    path('admin_console/permission/', include(permission_pattern)),
    path('admin_console/permission/', include(role_permission_pattern)),
    path('admin_console/permission/', include(user_role_pattern)),
    path('admin_console/configuration/', include(configuration_pattern)),

]

shared_storage/urls.py
from django.urls import path

from shared_storage import views
from django.conf.urls import include

app_name = 'shared_storage'

compare_pattern = [
    path('select', views.select_to_compare_page, name="select-to-compare-page"),
    path('result/<str:root_key>', views.select_to_compare_result_page,
         name="select-to-compare-result-page"),
    path('file/diff/<str:root_key>/<str:node_key>/<str:type>', views.select_to_compare_file_diff_page,
         name="select-to-compare-file-diff-page"),
    path('file/detail/<str:side>/<str:root_key>/<str:node_key>/<str:diff_result>/<str:file_type>',
         views.select_to_compare_file_detail_page, name="select-to-compare-file-detail-page"),
    path('mail', views.send_compare_result_mail),
]

download_pattern = [
    path('', views.select_to_download_page, name="select-to-download-page"),
    path('with/filters', views.select_to_download_filter_result_page, name="select-to-download-filter-result"),
    path('with/file/list', views.select_to_download_file_list_page, name="select-to-download-file-list"),
    path('files', views.download_files, name="select-to-download-files"),
    path('exist/files', views.download_exist_files, name="select-to-download-exist-files"),

]

filter_pattern = [
    path('compare/environment', views.select_to_compare_filter_environment,
         name="compare-filter-region-environments"),
    path('download/environment', views.select_to_download_filter_environment,
         name="download-filter-region-environments"),
    path('compare/folder', views.select_to_compare_filter_folder,
         name="compare-filter-environment-folders"),
    path('download/folder', views.select_to_download_filter_folder,
         name="download-filter-environment-folders"),
    path('download/module/folder', views.select_to_download_filter_module_folder,
         name="download-filter-folder-modules"),
    path('download/latest/version/folder', views.select_to_download_filter_latest_version_folder,
         name="download-filter-latest-version-folder"),
]

admin_console_pattern = [
    path('', views.admin_console_page, name="admin-console-index"),
    path('report/scheduler/list', views.admin_console_report_scheduler_list_page, name="report-scheduler-list-page"),
    path('report/scheduler/create', views.admin_console_report_scheduler_create_page,
         name="report-scheduler-create-page"),
    path('report/scheduler/update/<int:scheduler_id>', views.admin_console_report_scheduler_update_page,
         name="report-scheduler-update-page"),
]

admin_console_report_api_pattern = [
    path('run', views.run_report_scheduler_job, name="run-report-scheduler"),
    path('create', views.create_report_scheduler_job, name="create-report-scheduler"),
    path('update', views.update_report_scheduler_job, name="update-report-scheduler"),
    path('delete', views.delete_report_scheduler_job, name="delete-report-scheduler"),
    path('update_status', views.update_report_scheduler_status, name="update-report-scheduler-status"),
]

urlpatterns = [
    path('shared_storage/compare/', include(compare_pattern)),
    path('shared_storage/download/', include(download_pattern)),
    path('shared_storage/filter/', include(filter_pattern)),
    path('shared_storage/report/scheduler/', include(admin_console_report_api_pattern)),
    path('admin_console/shared_storage/', include(admin_console_pattern)),

]

shared_storage/views.py
import os

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse, Http404

from ConfigManageTool.settings import CURRENT_REGION
from RulesetComparer.utils.threadManager import run_in_background
from shared_storage.data_object.json_builder.report_scheduler_create_page import ReportSchedulerCreatePageBuilder
from shared_storage.data_object.json_builder.shared_storage_report_scheduler import SharedStorageSchedulersBuilder, \
    SharedStorageReportSchedulerBuilder
from shared_storage.data_object.json_builder.report_scheduler_update_page import ReportSchedulerUpdatePageBuilder
from RulesetComparer.properties.key import *
from RulesetComparer.utils.logger import info_log
from common.data_object.error.status import NOT_SUPPORT_PREVIEW, SUCCESS_NO_DATA
from common.data_object.json_builder.response import ResponseBuilder
from common.utils.utility import get_post_request_json
from common.views import page_error_check, action_error_check, page_permission_check, action_permission_check
from permission.utils.permission_manager import check_function_visibility
from shared_storage.data_object.json_builder.admin_console_info_builder import AdminConsoleInfoBuilder
from shared_storage.properties.config import COMPARE_TYPE_WHITE_LIST
from shared_storage.services import compare_services, download_services

from shared_storage.data_object.json_builder.bind_file_diff_result_builder import BindFolderFileDiffResultBuilder
from shared_storage.data_object.json_builder.bind_file_detail_builder import BindFileDetailBuilder, \
    BindFileSameDetailBuilder
from shared_storage.utils.file_manager import load_folder_file_diff_json
from shared_storage.models import SharedStorageReportScheduler
from shared_storage.services import report_scheduler_services


# backend page
@login_required
def admin_console_page(request):
    data = {KEY_NAVIGATION_INFO: AdminConsoleInfoBuilder(request.user).get_data()}
    return render(request, "shared_storage_admin_console_base.html", data)


@login_required
def admin_console_report_scheduler_list_page(request):
    def check_visibility():
        check_function_visibility(request, KEY_F_REPORT_TASK, KEY_M_SHARED_STORAGE)

    def get_visible_data():
        return SharedStorageReportScheduler.objects.get_visible_schedulers(request.user.id)

    def after_check(visible_data):
        data = SharedStorageSchedulersBuilder(request.user, visible_data).get_data()
        return render(request, "shared_storage_report_scheduler_list.html", data)

    return page_permission_check(request, check_visibility, get_visible_data, after_check)


@login_required
def admin_console_report_scheduler_create_page(request):
    def check_visibility():
        check_function_visibility(request, KEY_F_REPORT_TASK, KEY_M_SHARED_STORAGE)

    def get_visible_data():
        regions = compare_services.get_active_region_list()
        return regions

    def after_check(visible_data):
        data = ReportSchedulerCreatePageBuilder(request.user, visible_data).get_data()
        return render(request, "shared_storage_report_scheduler_create.html", data)

    return page_permission_check(request, check_visibility, get_visible_data, after_check)


@login_required
def admin_console_report_scheduler_update_page(request, scheduler_id):
    def check_visibility():
        check_function_visibility(request, KEY_F_REPORT_TASK, KEY_M_SHARED_STORAGE)

    def get_visible_data():
        regions = compare_services.get_active_region_list()
        return regions

    def after_check(visible_data):
        data = ReportSchedulerUpdatePageBuilder(request.user, visible_data, scheduler_id).get_data()
        return render(request, "shared_storage_report_scheduler_update.html", data)

    return page_permission_check(request, check_visibility, get_visible_data, after_check)


# frontend page
def select_to_compare_page(request):
    def after_check():
        if request.method == REQUEST_GET:
            regions = compare_services.get_active_region_list()
            response = ResponseBuilder(data=regions).get_data()
            return render(request, "select_to_compare.html", response)
        elif request.method == REQUEST_POST:
            left_region_id = request.POST.get('left_region_id')
            left_environment_id = request.POST.get('left_environment_id')
            left_folder = request.POST.get('left_folder')
            right_region_id = request.POST.get('right_region_id')
            right_environment_id = request.POST.get('right_environment_id')
            right_folder = request.POST.get('right_folder')
            #
            result_json = compare_services.compare_shared_storage_folder(left_region_id, left_environment_id,
                                                                         left_folder, right_region_id,
                                                                         right_environment_id, right_folder, False)
            #
            response = ResponseBuilder(data=result_json).get_data()
            return render(request, "shared_storage_folder_compare_result.html", response)

    return page_error_check(after_check)


def select_to_compare_filter_environment(request):
    def after_check():
        request_json = get_post_request_json(request)
        result_json = compare_services.get_region_environment_list(request_json)
        return render(request, "select_to_compare_dropdown.html", result_json)

    return page_error_check(after_check)


def select_to_compare_filter_folder(request):
    def after_check():
        request_json = get_post_request_json(request)
        result_json = compare_services.get_environment_dir_list(request_json)
        return render(request, "select_to_compare_dropdown.html", result_json)

    return page_error_check(after_check)


def select_to_compare_result_page(request, root_key):
    def after_check():
        result_json = load_folder_file_diff_json(root_key)
        response = ResponseBuilder(data=result_json).get_data()
        return render(request, "shared_storage_folder_compare_result.html", response)

    return page_error_check(after_check)


def select_to_compare_file_diff_page(request, root_key, node_key, type):
    def after_check():
        if type not in COMPARE_TYPE_WHITE_LIST:
            result = ResponseBuilder(status_code=NOT_SUPPORT_PREVIEW).get_data()
            return JsonResponse(result)
        else:
            result_json = BindFolderFileDiffResultBuilder(root_key, node_key).get_data()
            if type == KEY_PROPERTIES:
                response = ResponseBuilder(data=result_json).get_data()
                return render(request, "shared_storage_properties_file_diff.html", response)
            else:
                response = ResponseBuilder(data=result_json).get_data()
                return render(request, "shared_storage_string_file_diff.html", response)

    return page_error_check(after_check)


def select_to_compare_file_detail_page(request, side, root_key, node_key, diff_result, file_type):
    def after_check():
        if file_type not in COMPARE_TYPE_WHITE_LIST:
            result = ResponseBuilder(status_code=NOT_SUPPORT_PREVIEW).get_data()
            return JsonResponse(result)

        if diff_result == "same":
            result_json = BindFileSameDetailBuilder(side, root_key, node_key).get_data()
        else:
            result_json = BindFileDetailBuilder(side, root_key, node_key).get_data()

        response = ResponseBuilder(data=result_json).get_data()
        return render(request, "shared_storage_file_detail.html", response)

    return page_error_check(after_check)


def select_to_download_page(request):
    def after_check():
        regions = compare_services.get_active_region_list()
        response = ResponseBuilder(data=regions).get_data()
        return render(request, "select_to_download.html", response)

    return page_error_check(after_check)


def select_to_download_filter_environment(request):
    def after_check():
        request_json = get_post_request_json(request)
        result_json = download_services.get_region_environment_list(request_json)
        return render(request, "dropdown_component.html", result_json)

    return page_error_check(after_check)


def select_to_download_filter_folder(request):
    def after_check():
        request_json = get_post_request_json(request)
        result_json = download_services.get_environment_dir_list(request_json)
        return render(request, "dropdown_component.html", result_json)

    return page_error_check(after_check)


def select_to_download_filter_module_folder(request):
    def after_check():
        request_json = get_post_request_json(request)
        result_json = download_services.filter_second_folder(request_json)
        return render(request, "dropdown_component.html", result_json)

    return page_error_check(after_check)


def select_to_download_filter_latest_version_folder(request):
    def after_check():
        request_json = get_post_request_json(request)
        result_json = download_services.filter_latest_version_folder(request_json)
        return render(request, "dropdown_component.html", result_json)

    return page_error_check(after_check)


def select_to_download_filter_result_page(request):
    def after_check():
        request_json = get_post_request_json(request)
        result_json = download_services.filter_file_result(request_json)
        result_data_list = result_json.get(KEY_DATA)
        if len(result_data_list) == 0:
            result = ResponseBuilder(status_code=SUCCESS_NO_DATA).get_data()
            return JsonResponse(result)
        else:
            return render(request, "download_filter_result.html", result_json)

    return page_error_check(after_check)


def select_to_download_file_list_page(request):
    def after_check():
        request_json = get_post_request_json(request)

templates/shared_storage/frontend/select_to_compare.html
{% extends "shared_storage_front_base.html" %}
{% load staticfiles %}

{% block resource %}
    <link href="{% static '/css/shared_storage/select-to-compare.css' %}" rel="stylesheet">
    <link href="{% static '/css/shared_storage/shared-storage-folder-compare-result.css' %}" rel="stylesheet">
    <script src="{% static '/js/shared_storage/select_to_compare.js' %}"></script>
    <script src="{% static '/js/component/compare_region_dropdowns.js' %}"></script>
    <script src="{% static '/js/component/compare_environment_dropdowns.js' %}"></script>
    <script src="{% static '/js/component/compare_folder_dropdowns.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="select_to_compare_container" class="container-fluid">
        <p class="header-text">Compare</p>
        <div class="row no-row-margin">
            <div id="left_data_div">
                <div id="left_region_dropdown_div" class="dropdown-block">
                    <div class="drop_down_label_text" for="select_country">Data Center</div>
                    <div id="left_select_region" class="custom-btn-group-1 btn-group">
                        <button id="left_select_region_btn"
                                class="drop_down_button_width custom-dropdown-btn-1 btn btn-inverse dropdown-toggle"
                                type="button" data-toggle="dropdown">
                            Select
                        </button>
                        <ul id="left_select_region_list" class="dropdown-limit dropdown-menu dropdown-menu-inverse"
                            role="menu">
                            {% for region in data %}
                                <li value="{{ region.id }}"><a href="#">{{ region.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div id="left_environment_dropdown_div" class="dropdown-block">
                    {% with type="environment" side="left" title="Environment" data="" %}
                        {% include 'select_to_compare_dropdown.html' %}
                    {% endwith %}
                </div>
                <div id="left_folder_dropdown_div" class="dropdown-block">
                    {% with type="folder" side="left" title="Folder" data="" %}
                        {% include 'select_to_compare_dropdown.html' %}
                    {% endwith %}
                </div>
            </div>
            <div id="right_data_div">
                <div id="right_region_dropdown_div" class="dropdown-block">
                    <div class="drop_down_label_text" for="select_country">Data Center</div>
                    <div id="right_select_region" class="custom-btn-group-1 btn-group">
                        <button id="right_select_region_btn"
                                class="drop_down_button_width custom-dropdown-btn-1 btn btn-inverse dropdown-toggle"
                                type="button" data-toggle="dropdown">
                            Select
                        </button>
                        <ul id="right_select_region_list" class="dropdown-limit dropdown-menu dropdown-menu-inverse"
                            role="menu">
                            {% for region in data %}
                                <li value="{{ region.id }}"><a href="#">{{ region.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div id="right_environment_dropdown_div" class="dropdown-block">
                    {% with type="environment" side="right" title="Environment" data="" %}
                        {% include 'select_to_compare_dropdown.html' %}
                    {% endwith %}
                </div>
                <div id="right_folder_dropdown_div" class="dropdown-block">
                    {% with type="folder" side="right" title="Folder" data="" %}
                        {% include 'select_to_compare_dropdown.html' %}
                    {% endwith %}
                </div>
            </div>
        </div>

        <form id="compare" method="post">
            {% csrf_token %}
            <input name='left_region_id' id="left_region_id" value="" type="hidden">
            <input name='right_region_id' id="right_region_id" value="" type="hidden">
            <input name='left_environment_id' id="left_environment_id" value="" type="hidden">
            <input name='right_environment_id' id="right_environment_id" value="" type="hidden">
            <input name='left_folder' id="left_folder" value="" type="hidden">
            <input name='right_folder' id="right_folder" value="" type="hidden">

            <button id="compare_submit_button" class="custom-btn-1 btn btn-embossed btn-primary" type="submit"
                    form="compare" value="Submit">
                Submit
            </button>
        </form>
    </div>
    <script>
        setFilterEnvironmentUrl("{% url 'shared_storage:compare-filter-region-environments' %}");
        setFilterFolderUrl("{% url 'shared_storage:compare-filter-environment-folders' %}");
    </script>
{% endblock %}

templates/shared_storage/frontend/select_to_download.html
{% extends "shared_storage_front_base.html" %}
{% load staticfiles %}

{% block resource %}
    <link href="{% static '/css/shared_storage/select-to-download.css' %}" rel="stylesheet">
    <link href="{% static '/css/shared_storage/download-file-folder-structure.css' %}" rel="stylesheet">
    <script src="{% static '/js/shared_storage/select_to_download.js' %}"></script>
    <script src="{% static '/js/shared_storage/download_filter_result.js' %}"></script>
    <script src="{% static '/js/shared_storage/download_file_list.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="select_to_download_container" class="container-fluid">
        <div id="select_data_div" class="white_block_div">
            <p class="header-text">Download</p>
            <div id="data_center_select_div" class="select_data_row_div row no-row-margin">
                <div class="select_data_title">Data Center</div>
                <div class="drop_down_div">
                    {% with type="region" data=data %}
                        {% include 'dropdown_component.html' %}
                    {% endwith %}
                </div>
            </div>
            <div id="environment_select_div" class="select_data_row_div row no-row-margin">
                <div class="select_data_title">Environment</div>
                <div class="drop_down_div">
                    {% with type="environment" data="" %}
                        {% include 'dropdown_component.html' %}
                    {% endwith %}
                </div>
            </div>
            <div id="folder_select_div" class="select_data_row_div row no-row-margin">
                <div class="select_data_title">Country</div>
                <div class="drop_down_div">
                    {% with type="folder"  data="" %}
                        {% include 'dropdown_component.html' %}
                    {% endwith %}
                </div>
            </div>
            <div id="module_select_div" class="select_data_row_div row no-row-margin">
                <div class="select_data_title">Module</div>
                <div class="drop_down_div">
                    {% with type="module" data="" %}
                        {% include 'dropdown_component.html' %}
                    {% endwith %}
                </div>
            </div>
            <div id="latest_version_select_div" class="select_data_row_div row no-row-margin">
                <div class="select_data_title">Version</div>
                <div class="drop_down_div">
                    {% with type="latest_version" data="" %}
                        {% include 'dropdown_component.html' %}
                    {% endwith %}
                </div>
            </div>
            <div id="filter_div" class="select_data_row_div row no-row-margin">
                <div class="select_data_title">Filter</div>
                <div class="drop_down_div">
                    <div id="filter_input_div" class="tagsinput-primary">
                        <input id="filter_tags_input" name="tagsinput" class="tagsinput" data-role="tagsinput"
                               placeholder="bre_translation / onepad / template...etc"
                               style="display: none;">
                    </div>
                </div>
            </div>
            <div id="filter_button_div">
                <button id="filter_btn" class="btn btn-default btn-wide"
                        onclick="onClickSearchButton('{% url 'shared_storage:select-to-download-filter-result' %}','{% url 'shared_storage:select-to-download-file-list' %}')">
                    Search
                </button>
            </div>
        </div>
        <div class="gray_background">
            <div id="filter_result_div" class="white_block_div">
                <div id="filter_result_header_div" class="header_div row no-row-margin">
                    <p id="filter_result_title" class="header_result_title header-text">Filter Result</p>
                    <div class="download_button_div row no_row_margin">
                        <div id="filter_result_download_selected_btn_div"
                             class="download_selected_btn_div download-icon no-col-padding">
                            <button id="filter_result_download_selected_btn"
                                    class="download_button_width btn btn-inverse btn-font-13"
                                    onclick="downloadFilterFiles()">Download(1)
                            </button>
                        </div>
                        <div id="filter_result_select_all_btn_div"
                             class="select_all_btn_div download-icon no-col-padding">
                            <button id="filter_result_select_all_btn"
                                    class="download_button_width btn btn-info btn-font-13"
                                    onclick="filteredFilesSelectAll()">Select All
                            </button>
                        </div>
                    </div>
                </div>
                <div id="filter_result_row_div">
                    <div id="filter_result_row_title_div" class="row_title_div row no-row-margin">
                        <div id="checkbox_title_div" class="row_checkbox_width filter_result_row_title_text"></div>
                        <div id="file_icon_title_div" class="row_file_icon_width filter_result_row_title_text"></div>
                        <div id="file_path_title_div" class="row_file_path_width filter_result_row_title_text">File
                        </div>
                        <div id="file_size_title_div" class=" row_file_size_width filter_result_row_title_text">Size
                        </div>
                        <div id="modification_time_title_div"
                             class="row_modification_time_width filter_result_row_title_text">
                            Modification Time
                        </div>
                    </div>
                    <div id="filter_result_row_data_div">
                        {# after filter will response download_filter_result.html #}
                    </div>
                </div>
            </div>
        </div>
        <div class="gray_background">
            <div id="file_list_div" class="white_block_div">
                <div id="file_list_header_div" class="header_div row no-row-margin">
                    <p id="file_list_title" class="header_result_title header-text">File List</p>
                    <div class="download_button_div row no_row_margin">
                        <div id="file_list_download_selected_btn_div"
                             class="download_selected_btn_div download-icon no-col-padding">
                            <button id="file_list_download_selected_btn"
                                    class="download_button_width btn btn-inverse btn-font-13"
                                    onclick="downloadListFiles()">Download(1)
                            </button>
                        </div>
                        <div id="file_list_select_all_btn_div" class="select_all_btn_div download-icon no-col-padding">
                            <button id="file_list_select_all_btn" class="download_button_width btn btn-info btn-font-13"
                                    onclick="fileListSelectAll()">Select All
                            </button>
                        </div>
                    </div>
                </div>
                <div id="file_list_data_div">
                    <div id="file_list_row_title_div" class="row_title_div row no-row-margin">
                        <div id="file_path_title_div" class="row_file_path_width filter_result_row_title_text">File
                        </div>
                        <div id="file_size_title_div" class=" row_file_size_width filter_result_row_title_text">Size
                        </div>
                        <div id="modification_time_title_div"
                             class="row_modification_time_width filter_result_row_title_text">
                            Modification Time
                        </div>
                    </div>
                    <div id="file_list_row_list_div">
                        {# after filter will response download_file_list.html #}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        initDownloadFileUrl("{% url 'shared_storage:select-to-download-files' %}");
        onRegionSelected = function (regionId) {
            filterEnvironments(regionId, "{% url 'shared_storage:download-filter-region-environments' %}");
        };
        onEnvironmentSelected = function () {
            filterFolders("{% url 'shared_storage:download-filter-environment-folders' %}");
        };
        onFolderSelected = function () {
            filterModuleFolders("{% url 'shared_storage:download-filter-folder-modules' %}")
        };
        onModuleSelected = function () {
            filterLatestVersionFolders("{% url 'shared_storage:download-filter-latest-version-folder' %}")
        };
        onClickDownloadButton = function () {
            downloadFilterFiles()
        }
    </script>
{% endblock %}

templates/shared_storage/frontend/shared_storage_front_base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static '/css/flat-ui.css' %}" rel="stylesheet">
    <link href="{% static '/css/sweetalert.css' %}" rel="stylesheet">
    <link href="{% static '/css/fontawesome/all.css' %}" rel="stylesheet">
    <link href="{% static '/css/main.css' %}" rel="stylesheet">
    <script src="{% static '/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static '/js/popper.js' %}"></script>
    <script src="{% static '/js/flat-ui.js' %}"></script>
    <script src="{% static '/js/application.js' %}"></script>
    <script src="{% static '/js/sweetalert.min.js' %}"></script>
    <script src="{% static '/js/main.js' %}"></script>
    <script src="{% static '/js/rest-client.js' %}"></script>

    {% block resource %}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-default navbar-expand-lg" role="navigation">
    <a class="navbar-brand" href="#">Shared Storage Manager</a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse-01"></button>
    <div class="collapse navbar-collapse" id="navbar-collapse-01">
        <ul class="nav navbar-nav mr-auto">
            <li class="active"><a href="{% url 'shared_storage:select-to-compare-page' %}">Compare</a></li>
            <li class="active"><a href="{% url 'shared_storage:select-to-download-page' %}">Download</a></li>
        </ul>
    </div>
</nav>
{% csrf_token %}
<div id="block_content_div">
    {% block content %}
    {% endblock %}
</div>
</body>
<script>
    initLoadingGIF("{% static '/icons/loading.gif' %}");
</script>
</html>